### ISSUE TITLE
There is no response about temperature in output_bonds

### ISSUE THREAD

**Issue by churchyuan** [sulcgroup/oxdna_analysis_tools#20]
I run `oat output_bonds inputMD trajectory_trap.dat > energy2.txt`.
And I find each term of energy seems no change when I increase temperature. It is strange. Then I change the Temperature in input file to 100C and run it again. And I found there is also no difference, meaning the code does not read the Temperature.
And if I change the salt concentration, the energy can change reasonably.

**Comment by ErikPoppleton** [comment]
Most of the potential is not temperature dependent for the same configuration. The full forms of the potential can be found in appendix A of the [original paper](https://aip.scitation.org/doi/10.1063/1.3552946), with the exception of the electrostatic potential which can be found in [the followup](https://aip.scitation.org/doi/10.1063/1.4921957). Only the Debye-Hückel potential used for electrostatics is weakly temperature dependent. However, if you are running at high salt concentration as is generally done, the Debye length is going to be quite short and thus only a small change in the overall potential is to be expected. 

The changes in structure observed at higher temperatures (melting) are due to the thermostat, not the interactions changing (with the exception of electrostatics)

**Comment by churchyuan** [comment]
Thanks a lot!
