### ISSUE TITLE
Importing Problem with oxDNA_analysis_tools

### ISSUE THREAD

**Issue by Mehdiasr** [sulcgroup/oxdna_analysis_tools#24]
when i am trieng to import from oxDNA_analysis_tools i get this error: ModuleNotFoundError: No module named 'oxDNA_analysis_tools.UTILS.get_confs' Note: oxdna kernal is activated, i tried to pip install oxDNA_analysis_tools but it was already there, Also, i compiled file "get_confs" again and appended its path to code but the problem persists. "oat config" output: (oxdna) [sutei081@nesh-fe3 medhi_gen_algo]$ oat config
INFO: oxDNA_analysis_tools version: 2.2.1
INFO: running config.py installed at:  /gxfs_home/cau/sutei081/miniconda3/envs/oxdna/lib/python3.9/site-packages/oxDNA_analysis_tools/config.py
INFO: Python version: 3.9.17
INFO: Package Numpy found. Version: 1.25.2
INFO: Package MatPlotLib found. Version: 3.7.2
INFO: Package SciKit-Learn found. Version: 1.3.0
INFO: Package oxpy found. Version: 3.3
INFO: No dependency issues found.

INFO: Analyses will be computed in chunks of 20 configurations at a time
INFO: You can modify this number by running oat config -n <number>, which will be persistent between analyses.
(oxdna) [sutei081@nesh-fe3 medhi_gen_algo]$

**Comment by ErikPoppleton** [comment]
Weird, never seen this one before.  Can you give me a little more information about what you're trying to do?  Usually the way to import `get_confs` is through RyeReader (`from oxDNA_analysis_tools.UTILS.RyeReader import get_confs`) so that you can have typing and completion hints in IDEs, but `from oxDNA_analysis_tools.UTILS.get_confs import cget_confs` should work (since that's what RyeReader itself uses)

Can you also double check that running the other scripts works? For example go to a directory with a trajectory file and run `oat mean trajectory.dat`.

**Comment by ErikPoppleton** [comment]
Also, I just realized this is the old repository from before `oat` was merged into oxDNA.  Based on your version number it looks like you're using the version which comes with oxDNA, but just want to make sure you know that this repository is only here for archival purposes and it hasn't been updated in over a year.

**Comment by Mehdiasr** [comment]
Hello Eric, Thanks for your response. The problem has been fixed, i guess, it was because i copied the oat folder to my directory separately. I am trying to obtain the distance between two nucleotides, specifically the first nucleotide from the first strand and the last nucleotide from the second strand, which I am attempting to do using 'distance.py'.
